remote_theme: KevinWMatthews/minima
title: c/cpputest_intro
description:
  TDD in C using CppUTest.
  Configure with CMake.
  Run with Docker.
author: Kevin W Matthews
author_url: https://www.kevinwmatthews.com
header_pages:
  - system-tools.md
  - docker.md
